### ISSUE TITLE
Sample Invoice

### ISSUE THREAD

**Issue by patagoniahiker** [SUKOHI/jquery.inline-edit#1]
Hello, I was playing around and trying to do a sample invoice, that contains row of items etc. Can you please add that as a sample, it would cover the various datatypes and also show how to use the plugin in the entire page.

**Comment by SUKOHI** [comment]
Hi, patagoniahiker.
Thank you for your message.

I've just added a sample you want.
I'm glad if it would be useful for you.:)

**Comment by patagoniahiker** [comment]
thanks  :+1: is it also possible to let use upload an image, for e.g. like a logo in place?

**Comment by SUKOHI** [comment]
Unfortunately, this package doesn't support to upload images, sorry.
But I guess jquery-file-upload can help you.

https://github.com/blueimp/jQuery-File-Upload
